import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Fortrans</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="Fortrans, ForTrans, fortrans, Team Fortrans" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script lang='js'></Script> */}
      {/* <Script src='/sc.js' strategy='lazyOnload' /> */}
      <nav className={styles.mainnav}>
        <ul>
          <li>Home</li>
          <li>About</li>
          <li>Blog</li>
          <li>Contacts</li>
        </ul>
      </nav>
      <main className={styles.main}>
        <h1 className={styles.title}>
          <code className={styles.code}>ForTrans</code> Blog
        </h1>

        <p className={styles.description}>
          Powered by <code className={styles.code}>ForTrans</code>
        </p>

        <div className="blogs">
          <h2>Popular Blogs</h2>
          <div className="blogItem">
            <h1>How to learn Python in 2022?</h1>
            <p>Python programming is very easy.</p>
          </div>
          <div className="blogItem">
            <h1>How to learn Python in 2022?</h1>
            <p>Python programming is very easy.</p>
          </div>
          <div className="blogItem">
            <h1>How to learn Python in 2022?</h1>
            <p>Python programming is very easy.</p>
          </div>
        </div>
      </main>


      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
